# Generated by Django 4.2.13 on 2024-06-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilerequest_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilerequest',
            name='group',
        ),
    ]
