# Generated by Django 4.2.13 on 2024-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profilerequest_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerequest',
            name='picture',
            field=models.ImageField(default='', upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
