# Generated by Django 4.2.13 on 2024-06-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilerequest_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileRequest',
        ),
    ]
