# Generated by Django 4.2.13 on 2024-06-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profilerequest_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerequest',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
