# Generated by Django 4.2.13 on 2024-06-21 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_rename_content_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reciptient',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
