# Generated by Django 4.2.13 on 2024-06-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_reciptient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciptient',
            new_name='reciptients',
        ),
    ]
